### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by rrkotik** [DeMaCS-UNICAL/I-DLV-sr#1]
hi, is source code available for "I-DLV-sr-v1.0.jar" ?

**Comment by GitElena** [comment]
Hi, at the moment the source code is private. However, if you have any curiosity or questions about specific aspects of the implementation, feel free to ask. We will be available to discuss it.

**Comment by rrkotik** [comment]
Thanks for the answer, was curious about distributed reasoning, details of implementation. Also, are you planning to  release code or keep your product for sale?

**Comment by GitElena** [comment]
No, we have no plans to release the code yet. You can find (i) the first release of the system here: [release](https://github.com/DeMaCS-UNICAL/I-DLV-sr/releases/tag/v1.0); and (ii) its description here: https://arxiv.org/abs/2108.02797

**Comment by rrkotik** [comment]
What about commercial usage?

**Comment by kaliaragorn** [comment]
Dear rrkotik,

We have no short-term roadmaps; nevertheless, we plan to further
engineering the product for industrial/commercial use.

are you interested in a commercial application?
f

**Comment by rrkotik** [comment]
IDLVSR is one of the options. first of all, need to understand the performance. what IDLVSR performance on city benchmark for single machine and for distributed case?

**Comment by kaliaragorn** [comment]
Dear rrkotik,

what do you mean with city benchmarks?
also, what kind of options are you referring to?
f

**Comment by rrkotik** [comment]
Dear kaliaragorn,
by city benchmark i mean https://github.com/CityBench/Benchmark
other options are cqels and csparql

**Comment by kaliaragorn** [comment]
Dear rrkotik,

unfortunately, we did not test city benchmark yet.
we are planning to either adapt it or see how to extend the system for
accessing rdf-like data; no precise roadmap has been defined yet, though.

if you want, you can start testing it: we can support you with this.

just let us know.

ciao
f
